### ISSUE TITLE
Problème d'autocomplétion si le lexème à compléter contient un accent

### ISSUE THREAD

**Issue by delthas** [emersion/atom-language-c-fr#1]
Bonjour,

Tout d'abord merci pour le développement de cette fantastique extension pour Atom permettant de coder dans son langage préféré, avec son langage préféré.

J'ai un bogue à rapporter. Lors de l'autocomplétion d'un lexème, si celui-ci contient (avant la complétion) un caractère accentué, l'autocomplétion ajoutera l'intégralité du lexème (au lieu simplement de la suite du lexème) après l'accent.

Voici un exemple simple permettant de reproduire ce bogue :
- Créer un fichier main.c.fr dans Atom et activer le langage c.fr
- Ecrire quelque part dans le fichier un lexème contenant un accent, par exemple: mémoire_lecture.
- Commencer à écrire, à un autre endroit : "mém", puis sélectionner dans la fenêtre d'autocomplétion l'entrée mémoire_lecture.

Ce qui est attendu : le mot "mém" est remplacé par "mémoire_lecture".

Ce qui se déroule : le mot "mém" est remplacé par "**mé**mémoire_lecture".

Merci,
Cordialement,

Jacqueline Jacquiez du canton de La Tourraine,
Présidente du club de Boules de la communauté d'agglomération de La Tourraine,
Amateur de l'usage de la langue Française,
Membre émérite du club de Boules de la communauté d'agglomération de La Tourraine,
Mère de deux enfants, Brigitte et Pascal,
Fille de deux parents, Birgitte et Java,
Propriétaire d'un chien de garde d'une lignée japonaise.

**Comment by delthas** [comment]
Bonne journé
# e @emersion 

> Cordialement

**Comment by emersion** [comment]
C'est un bogue d'Atom malheureusement.
